/**
 * Plain-text exports for a ProductHandoff. These only produce text for the clipboard —
 * there is no Slack, Jira or other external integration.
 */
import type { ProductHandoff } from './types';

const SYNTHETIC_NOTE = 'Synthetic data — portfolio prototype. Not Circle customer data.';
const PRIORITY_NOTE = 'Prototype priority — not Circle’s internal priority policy.';
const REC_LABEL = 'Prototype recommendation · synthetic data';

/** Concise Slack-ready message (Slack mrkdwn). */
export function formatForSlack(h: ProductHandoff): string {
  return [
    `:mag: *Product feedback signal:* ${h.title}`,
    `_${SYNTHETIC_NOTE}_`,
    '',
    `*Problem:* ${h.problem}`,
    `*Evidence:* ${h.evidence.map((e) => e.id).join(', ')}`,
    `*Pattern:* ${h.observedPattern[1]}`,
    `*Suggested investigation (${REC_LABEL}):* ${h.suggestedInvestigation}`,
    `*Suggested priority:* ${h.priority.level} — ${h.priority.route} (${PRIORITY_NOTE})`,
    '',
    `:warning: ${h.humanReview}`,
  ].join('\n');
}

/** Structured issue text (Jira wiki markup). */
export function formatForJira(h: ProductHandoff): string {
  const list = (items: string[]) => items.map((i) => `* ${i}`).join('\n');
  return [
    `Summary: ${h.title}`,
    'Issue type: Investigation (suggested)',
    `Priority: ${h.priority.level} (${PRIORITY_NOTE})`,
    'Labels: support-signal, synthetic-data, portfolio-prototype',
    '',
    `{panel:title=Data notice}${SYNTHETIC_NOTE} ${h.humanReview}{panel}`,
    '',
    'h3. Problem',
    h.problem,
    '',
    'h3. Customer impact',
    list(h.customerImpact),
    '',
    'h3. Evidence',
    list(h.evidence.map((e) => `${e.id} — ${e.subject} (${e.createdAt}, ${e.severity}, ${e.status})`)),
    '',
    'h3. Observed pattern',
    list(h.observedPattern),
    '',
    'h3. What support tried',
    list(h.supportTried),
    '',
    `h3. Suggested investigation (${REC_LABEL})`,
    h.suggestedInvestigation,
    '',
    'h3. Priority rationale',
    list([`Route: ${h.priority.route}`, ...h.priority.reasons]),
    ...(h.relatedDocs.length ? ['', 'h3. Related public Circle documentation', list(h.relatedDocs.map((d) => `[${d.title}|${d.url}]`))] : []),
    '',
    h.source,
  ].join('\n');
}

/** Complete report (Markdown). */
export function formatReport(h: ProductHandoff): string {
  const list = (items: string[]) => items.map((i) => `- ${i}`).join('\n');
  return [
    `# Product handoff: ${h.title}`,
    '',
    `> ${SYNTHETIC_NOTE}`,
    `> ${h.humanReview}`,
    '',
    '## 1. Title',
    h.title,
    '',
    '## 2. Problem',
    h.problem,
    '',
    '## 3. Customer impact',
    list(h.customerImpact),
    '',
    '## 4. Evidence',
    list(h.evidence.map((e) => `${e.id} — ${e.subject} (${e.createdAt}, ${e.severity}, ${e.status})`)),
    '',
    '## 5. Observed pattern',
    list(h.observedPattern),
    '',
    '## 6. What support tried',
    list(h.supportTried),
    '',
    `## 7. Suggested investigation (${REC_LABEL})`,
    h.suggestedInvestigation,
    '',
    '## 8. Priority',
    `${h.priority.level} — ${h.priority.route}. ${PRIORITY_NOTE}`,
    list(h.priority.reasons),
    ...(h.relatedDocs.length ? ['', '## Related public Circle documentation', list(h.relatedDocs.map((d) => `${d.title} — ${d.url}`))] : []),
    '',
    '## 9. Source',
    h.source,
    '',
    '## 10. Human review',
    h.humanReview,
    '',
    `_Generated by ${h.generatedFrom}._`,
  ].join('\n');
}
